<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLiPizza" Class="PizzaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\mssqllocaldb;Initial Catalog=QuanLiPizza;Integrated Security=True;Pooling=False" SettingsObjectName="ProjectManagementPizza.Properties.Settings" SettingsPropertyName="QuanLiPizzaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="category_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="category_pizza" Member="pizzas" ThisKey="category_id" OtherKey="category_id" Type="pizza" />
    </Type>
  </Table>
  <Table Name="dbo.commune" Member="communes">
    <Type Name="commune">
      <Column Name="commune_id" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="commune_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="degree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="district_id" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Association Name="commune_customer" Member="customers" ThisKey="commune_id" OtherKey="commune_id" Type="customer" />
      <Association Name="commune_staff" Member="staffs" ThisKey="commune_id" OtherKey="commune_id" Type="staff" />
      <Association Name="commune_warehouse" Member="warehouses" ThisKey="commune_id" OtherKey="commune_id" Type="warehouse" />
      <Association Name="district_commune" Member="district" ThisKey="district_id" OtherKey="district_id" Type="district" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customer_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="commune_id" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Association Name="customer_order" Member="orders" ThisKey="customer_id" OtherKey="customer_id" Type="order" />
      <Association Name="commune_customer" Member="commune" ThisKey="commune_id" OtherKey="commune_id" Type="commune" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.district" Member="districts">
    <Type Name="district">
      <Column Name="district_id" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="district_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="province_id" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="district_commune" Member="communes" ThisKey="district_id" OtherKey="district_id" Type="commune" />
      <Association Name="province_district" Member="province" ThisKey="province_id" OtherKey="province_id" Type="province" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.login" Member="logins">
    <Type Name="login">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.order_detail" Member="order_details">
    <Type Name="order_detail">
      <Column Name="order_detail_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unit_price" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="order_order_detail" Member="order" ThisKey="order_id" OtherKey="order_id" Type="order" IsForeignKey="true" />
      <Association Name="product_order_detail" Member="product" ThisKey="product_id" OtherKey="product_id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.pizza" Member="pizzas">
    <Type Name="pizza">
      <Column Name="pizza_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pizza_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pizza_description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="price_small" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_medium" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_large" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="category_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="category_pizza" Member="category" ThisKey="category_id" OtherKey="category_id" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.province" Member="provinces">
    <Type Name="province">
      <Column Name="province_id" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="province_name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="province_district" Member="districts" ThisKey="province_id" OtherKey="province_id" Type="district" />
    </Type>
  </Table>
  <Table Name="dbo.staff" Member="staffs">
    <Type Name="staff">
      <Column Name="staff_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="staff_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="commune_id" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="salary" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="staff_order" Member="orders" ThisKey="staff_id" OtherKey="staff_id" Type="order" />
      <Association Name="commune_staff" Member="commune" ThisKey="commune_id" OtherKey="commune_id" Type="commune" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.warehouse" Member="warehouses">
    <Type Name="warehouse">
      <Column Name="warehouse_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="warehouse_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="street" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="commune_id" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Association Name="commune_warehouse" Member="commune" ThisKey="commune_id" OtherKey="commune_id" Type="commune" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.orders" Member="orders">
    <Type Name="order">
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="staff_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="order_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="order_order_detail" Member="order_details" ThisKey="order_id" OtherKey="order_id" Type="order_detail" />
      <Association Name="customer_order" Member="customer" ThisKey="customer_id" OtherKey="customer_id" Type="customer" IsForeignKey="true" />
      <Association Name="staff_order" Member="staff" ThisKey="staff_id" OtherKey="staff_id" Type="staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.product" Member="products">
    <Type Name="product">
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="unit_price" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="image" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="product_order_detail" Member="order_details" ThisKey="product_id" OtherKey="product_id" Type="order_detail" />
    </Type>
  </Table>
</Database>